package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// Warm Parchment & Gold Palette (Sacred & Editorial)
val BibleAmberPrimary = Color(0xFF8D5B29)
val BibleAmberPrimaryDark = Color(0xFFE5B374)
val BibleGoldAccent = Color(0xFFC89033)
val BibleNavyPrimary = Color(0xFF192A45)
val BibleDeepIndigo = Color(0xFF101926)

// Parchment Theme (Classic Readability)
val ParchmentBackground = Color(0xFFFAF6EE)
val ParchmentSurface = Color(0xFFF3ECE0)
val ParchmentSurfaceVariant = Color(0xFFE9DFC8)
val ParchmentTextPrimary = Color(0xFF2C241B)
val ParchmentTextSecondary = Color(0xFF6B5F51)
val ParchmentBorder = Color(0xFFDECFA8)

// Sepia Theme
val SepiaBackground = Color(0xFFF3EBDB)
val SepiaSurface = Color(0xFFE8DCBF)
val SepiaTextPrimary = Color(0xFF382A1C)
val SepiaTextSecondary = Color(0xFF6E5942)

// Night Theme
val NightBackground = Color(0xFF0F141C)
val NightSurface = Color(0xFF182230)
val NightSurfaceVariant = Color(0xFF243247)
val NightTextPrimary = Color(0xFFEBF1F9)
val NightTextSecondary = Color(0xFF9CADC3)
val NightBorder = Color(0xFF2E3D52)

// Highlight Colors
val HighlightGold = Color(0xFFFFE082)
val HighlightRose = Color(0xFFFFCDD2)
val HighlightEmerald = Color(0xFFC8E6C9)
val HighlightSky = Color(0xFFBBDEFB)
val HighlightLavender = Color(0xFFE1BEE7)
val HighlightPeach = Color(0xFFFFCCBC)

// M3 Theme Colors
val md_theme_light_primary = Color(0xFF84531E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB8)
val md_theme_light_onPrimaryContainer = Color(0xFF2B1700)
val md_theme_light_secondary = Color(0xFF705B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFBDFBC)
val md_theme_light_onSecondaryContainer = Color(0xFF271904)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABF)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCF8F2)
val md_theme_light_onBackground = Color(0xFF201B16)
val md_theme_light_surface = Color(0xFFFCF8F2)
val md_theme_light_onSurface = Color(0xFF201B16)
val md_theme_light_surfaceVariant = Color(0xFFF0E0CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4F4539)
val md_theme_light_outline = Color(0xFF817567)

val md_theme_dark_primary = Color(0xFFFFB95E)
val md_theme_dark_onPrimary = Color(0xFF472A00)
val md_theme_dark_primaryContainer = Color(0xFF653E07)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB8)
val md_theme_dark_secondary = Color(0xFFDEC3A1)
val md_theme_dark_onSecondary = Color(0xFF3E2D16)
val md_theme_dark_secondaryContainer = Color(0xFF56432B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFBDFBC)
val md_theme_dark_tertiary = Color(0xFFB8CEA4)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF141A22)
val md_theme_dark_onBackground = Color(0xFFECE1DA)
val md_theme_dark_surface = Color(0xFF141A22)
val md_theme_dark_onSurface = Color(0xFFECE1DA)
val md_theme_dark_surfaceVariant = Color(0xFF243040)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C4B4)
val md_theme_dark_outline = Color(0xFF9C8E80)
